singleQuote: true
semi: false
printWidth: 100
trailingComma: es5
tabWidth: 2
useTabs: false
bracketSpacing: true
bracketSameLine: false
arrowParens: avoid
endOfLine: lf
quoteProps: as-needed
jsxSingleQuote: true
proseWrap: preserve
htmlWhitespaceSensitivity: css
embeddedLanguageFormatting: auto
